<tab>:

    size_hint: .5,.5
    pos_hint: {'center_x':.5,'center_y':.5}
    do_default_tab: False

    TabbedPanelItem:
        text: "Tab 1"
        Label:
            text: "First Tab"

    TabbedPanelItem:
        text: "Tab 2"
        BoxLayout:
            Label:
                text: "Press Button"
            Button:
                text: "Click Me"

    TabbedPanelItem:
        text: "Tab 3"
        Label:
            text: "Third Tab"
